---

- name: 'Install OpenTelemetryCollector'
  hosts: 'k3s1'
  gather_facts: true
  become: false
  module_defaults:
    kubernetes.core.helm:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s_info:
      kubeconfig: './k3s-kubeconfig'

  tasks:

    - name: 'Install OpenTelemetryCollector via the helm chart'
      delegate_to: 'localhost'
      kubernetes.core.helm:
        chart_repo_url: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
        release_name: 'opentelemetry-collector'
        chart_ref: 'opentelemetry-collector'
        release_namespace: 'grafana-tempo'
        release_values:
          mode: deployment
          ingress:
            enabled: true
            hosts:
              - host: "opentelemetry-collector.{{ hostvars['k3s1']['ansible_default_ipv4']['address'] }}.sslip.io"
                paths:
                  - path: /
                    pathType: Prefix
                    port: 4318
          config:
            exporters:
              debug: {}
              otlp/grafana:
                endpoint: tempo:4317
                tls:
                  insecure: true
            service:
              pipelines:
                traces:
                  exporters:
                    - debug
                    - otlp/grafana
                  receivers:
                    - otlp

    - name: 'Output the URL'
      delegate_to: 'localhost'
      ansible.builtin.debug:
        msg: "The opentelemetry-collector is reachable at http://opentelemetry-collector.{{ hostvars['k3s1']['ansible_default_ipv4']['address'] }}.sslip.io:80"
