---

- name: 'Install the MinIO tenant'
  hosts: 'k3s1'
  gather_facts: true
  become: false
  module_defaults:
    kubernetes.core.helm:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s_info:
      kubeconfig: './k3s-kubeconfig'

  tasks:

    - name: 'Create the grafana-tempo namespace'
      kubernetes.core.k8s:
        name: 'grafana-tempo'
        api_version: 'v1'
        kind: 'Namespace'
        state: 'present'
      delegate_to: 'localhost'

    - name: 'Create the MinIO secret'
      kubernetes.core.k8s:
        state: 'present'
        resource_definition: |
          metadata:
            name: 'minio-vagrant-libvirt-user'
            namespace: 'grafana-tempo'
          api_version: 'v1'
          kind: 'Secret'
          stringData:
            CONSOLE_ACCESS_KEY: minio-vagrant-libvirt-user
            CONSOLE_SECRET_KEY: secret123
      delegate_to: 'localhost'

    - name: 'Install the MinIO tenant via the helm chart'
      kubernetes.core.helm:
        chart_repo_url: 'https://operator.min.io'
        release_name: 'minio-tenant'
        chart_ref: 'tenant'
        release_namespace: 'grafana-tempo'
        values:
          secrets:
              name: 'minio-vagrant-libvirt-env-configuration'
              accessKey: 'minio-vagrant-libvirt'
              secretKey: 'minio123'
          tenant:
            name: 'minio-vagrant-libvirt'
            configuration:
              name: 'minio-vagrant-libvirt-env-configuration'
            pools:
              - servers: 1
                volumesPerServer: 1
            certificate:
              requestAutoCert: false
            buckets:
              - name: 'vagrant-libvirt-test1'
            users:
              - name: 'minio-vagrant-libvirt-user'
          ingress:
            api:
              enabled: true
              host: "minio-api.tenant.{{ hostvars['k3s1']['ansible_default_ipv4']['address'] }}.sslip.io"
            console:
              enabled: true
              host: "minio-console.tenant.{{ hostvars['k3s1']['ansible_default_ipv4']['address'] }}.sslip.io"
      delegate_to: 'localhost'

    - name: 'Wait until MinIO Console URL is reachable'
      ansible.builtin.uri:
        url: "http://minio-console.tenant.{{ hostvars['k3s1']['ansible_default_ipv4']['address'] }}.sslip.io"
      register: result
      until: "result.status == 200"
      retries: 11
      delay: 10

    - name: 'Output console URL'
      ansible.builtin.debug:
        msg: "The MinIO tenant console is reachable at minio-console.tenant.{{ hostvars['k3s1']['ansible_default_ipv4']['address'] }}.sslip.io"
      delegate_to: 'localhost'

    - name: 'Output API URL'
      ansible.builtin.debug:
        msg: "The MinIO tenant API is reachable at minio-api.tenant.{{ hostvars['k3s1']['ansible_default_ipv4']['address'] }}.sslip.io"
      delegate_to: 'localhost'
